version: '3.1'

services:
  fitness:
    build: .
    restart: always
    ports:
      - "3000:3000"
    environment:
      - TOKEN_SECRET=fuh32f98h2fh
      - MONGO_URL=mongodb://mongo:27017
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./mongo_db:/data/db"
